sudo: required
language: node_js
node_js:
- '10'
before_install:
- yarn
script:
- yarn build
env:
  global:
  - secure: qKFFdjEtYefilcUd3vtoYuMvYhwhRzfuUoqv0+7D0niin+nvqBQ/WotPe00hBPdPH1M4Oz+jwHcMX4LxAcx5toLWg7Ul4HiXOvX7OhewxydNIfM71HdQnuG1peWX+jkFUYNpejiw8FchmVJYtElH+X3PaDwb0R5gA78OXaGBtv1dXCqsbQSZogEndfFpCv7gvYBmK5Agdk5kKgTAH5R3yYFWZ94kH/94T2fLYChigF2a6s6ljmkp7pEDVmlckjfpGzlcG+pHzwm0SCKzE3GfOSVYQSaZFuLT+kuqHpenJuIyLJgT6gK/WRW3TGesAPdfuRt0z1fsbQoaldojIqTb/8gBZxnX7Qu5fw987+UKfHavTcj2lrdCyuv3z/hprpk9Ps2KSW7bDMuXkRfCgomECXD66oIQKRBw5nklrL7jNeoIvKibw2p9kK63s3BBgXnsj2afOzqoGgISH8xf09m/7H/F4BiRqDPyzkHyfjAJ0ilL78unYZVXob47+mYle0DRjU3nQxLMZx61SI2jDGi4edzmp0N/BIiqRTMcogvXKoB7uk4cRBmOK4nFOlX/5aAFLueMglUcNGfkZaEUD5eU0Z+JQWCTe7KCHtJLF87L2P4yF78SLUd+piGUO70A4858naANkiKm/bZvQ1jRpdDhMQPev4ydUDo6LJffeDuHf1s=
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: /dist
  repo: JanssenZhang/vue-drag-select
  on:
    branch: master
